clean:
	rm -f *.mp4
	rm -rf workspace
all:
	make 41
	make 43
	make 44
	make 45
	make 46
46all:
	make 46
	make 461
	make 462
	make 463
41:
	cargo run settings/cnf1_sin.yaml
	python3 1d_mp4.py
	cargo run settings/cnf1_square.yaml
	python3 1d_mp4.py
# TODO 42
43:
	cargo run settings/cnf3_sin.yaml
	python3 1d_mp4.py
	cargo run settings/cnf3_square.yaml
	python3 1d_mp4.py
44:
	cargo run settings/cnf4_sin.yaml
	python3 1d_mp4.py
	cargo run settings/cnf4_square.yaml
	python3 1d_mp4.py
45:
	cargo run settings/cnf5_sin.yaml
	python3 1d_mp4.py
	cargo run settings/cnf5_square.yaml
	python3 1d_mp4.py
46:
	cargo run settings/cnf6_sin.yaml
	python3 1d_mp4.py
	cargo run settings/cnf6_square.yaml
	python3 1d_mp4.py
461:
	cargo run settings/cnf61_sin.yaml
	python3 1d_mp4.py
	cargo run settings/cnf61_square.yaml
	python3 1d_mp4.py
462:
	cargo run settings/cnf62_sin.yaml
	python3 1d_mp4.py
	cargo run settings/cnf62_square.yaml
	python3 1d_mp4.py
463:
	cargo run settings/cnf63_sin.yaml
	python3 1d_mp4.py
	cargo run settings/cnf63_square.yaml
	python3 1d_mp4.py
