# https://marui.hatenablog.com/entry/2020/01/14/001900
using Pkg

# Pkg.add("ACME")
# Pkg.add("ColorSchemeTools")
# Pkg.add("Documenter")
# Pkg.add("HDF5")
# Pkg.add("Interact")
# Pkg.add("PackageCompiler")
# Pkg.add("RCall")
# Pkg.add("RDatasets")
# Pkg.add("Suppressor")
Pkg.add("AbstractPlotting")
Pkg.add("Bootstrap")
Pkg.add("CSV")
Pkg.add("Calculus")
Pkg.add("CategoricalArrays")
Pkg.add("Clustering")
Pkg.add("DataFrames")
Pkg.add("DifferentialEquations")
Pkg.add("Distances")
Pkg.add("Distributions")
Pkg.add("DynamicHMC")
Pkg.add("FileIO")
Pkg.add("ForwardDiff")
Pkg.add("GLM")
Pkg.add("GR")
Pkg.add("GRUtils")
Pkg.add("HCubature")
Pkg.add("HypothesisTests")
Pkg.add("IJulia")
Pkg.add("ImageFiltering")
Pkg.add("ImplicitEquations")
Pkg.add("JLD2")
Pkg.add("KernelDensity")
Pkg.add("LanguageServer")
Pkg.add("LaTeXStrings")
Pkg.add("Lasso")
Pkg.add("LinearAlgebra")
Pkg.add("Loess")
Pkg.add("LogDensityProblems")
Pkg.add("MCMCDiagnostics")
Pkg.add("MLBase")
Pkg.add("Makie")
Pkg.add("MakieGallery")
Pkg.add("Mamba")
Pkg.add("Measures")
Pkg.add("MultipleTesting")
Pkg.add("MultivariateStats")
Pkg.add("NMF")
Pkg.add("Optim")
Pkg.add("Parameters")
Pkg.add("Plots")
Pkg.add("Primes")
Pkg.add("ProgressMeter")
Pkg.add("PyCall")
Pkg.add("PyPlot")
Pkg.add("QuadGK")
Pkg.add("Random")
Pkg.add("Revise")
Pkg.add("SimpleDirectMediaLayer")
Pkg.add("SpecialFunctions")
Pkg.add("Statistics")
Pkg.add("StatsBase")
Pkg.add("StatsFuns")
Pkg.add("StatsKit")
Pkg.add("StatsModels")
Pkg.add("StatsPlots")
Pkg.add("SymPy")
Pkg.add("TimeSeries")
Pkg.add("TransformVariables")

# Precompile
# Pkg.add(PackageSpec(url="https://github.com/JuliaLang/PackageCompiler.jl",rev="master"))
# Pkg.precompile()
