(let ()
  (print "B.2 名前と手続き")
  (print ((lambda (x) (* x x)) 5))
  (print ((((lambda (a)
            (lambda (b)
              (lambda (x)
                (+ (* a x) b)))) 2) 3) 5))
  (print ((lambda (a b x)
            (+ (* a x) b))
          2 3 5))
  "end")
